// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElSwitch: typeof import('element-plus/es')['ElSwitch']
}
export {}
